-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.clients
(
    id bigint NOT NULL,
    "UserID" character varying(5) NOT NULL,
    fname character varying(50) NOT NULL,
    lname character varying(50),
    dob date NOT NULL,
    gender character varying(6) NOT NULL,
    email character varying(50) NOT NULL,
    phone_number character varying(13) NOT NULL,
    password_serial_number character varying(9) NOT NULL,
    description text,
    image_path text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.packages
(
    id bigint NOT NULL,
    package_name text NOT NULL,
    image_path text NOT NULL,
    duration text NOT NULL,
    price real NOT NULL,
    days integer NOT NULL,
    description text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.memberships
(
    id bigint NOT NULL,
    client_id bigint NOT NULL,
    package_id bigint NOT NULL,
    instructor_id bigint NOT NULL,
    status text NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    payment_date timestamp without time zone NOT NULL,
    payment_status text NOT NULL,
    description text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.instructors
(
    id bigint NOT NULL,
    "InstructorID" character varying(5) NOT NULL,
    fname character varying(50) NOT NULL,
    lname character varying(50) NOT NULL,
    dob date NOT NULL,
    gender character varying(6) NOT NULL,
    salary real NOT NULL,
    email character varying(50) NOT NULL,
    title text NOT NULL,
    description text,
    phone_number character varying(13) NOT NULL,
    image_path text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.payments
(
    id bigint NOT NULL,
    client_id bigint NOT NULL,
    payment_type character varying(10) NOT NULL,
    description text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.admins
(
    id bigint NOT NULL,
    "AdminID" character varying(5) NOT NULL,
    fname character varying(50) NOT NULL,
    lname character varying(50) NOT NULL,
    dob date NOT NULL,
    gender character varying(6) NOT NULL,
    email character varying(50) NOT NULL,
    password text NOT NULL,
    phone_number character varying(13) NOT NULL,
    description text,
    image_path text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.attendance
(
    id bigint NOT NULL,
    client_id bigint NOT NULL,
    session_id bigint NOT NULL,
    description text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sessions
(
    id bigint NOT NULL,
    instructor_id bigint NOT NULL,
    membership_id bigint NOT NULL,
    destination_date date NOT NULL,
    is_attended boolean NOT NULL,
    description text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.memberships
    ADD FOREIGN KEY (client_id)
    REFERENCES public.clients (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.memberships
    ADD FOREIGN KEY (package_id)
    REFERENCES public.packages (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.memberships
    ADD FOREIGN KEY (instructor_id)
    REFERENCES public.instructors (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.payments
    ADD FOREIGN KEY (client_id)
    REFERENCES public.clients (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.attendance
    ADD FOREIGN KEY (client_id)
    REFERENCES public.clients (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.attendance
    ADD FOREIGN KEY (session_id)
    REFERENCES public.sessions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sessions
    ADD FOREIGN KEY (instructor_id)
    REFERENCES public.instructors (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sessions
    ADD FOREIGN KEY (membership_id)
    REFERENCES public.memberships (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;